// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, http, io, server;

  express = require('express');

  http = require('http');

  app = express();

  server = app.listen(2000);

  io = require('socket.io').listen(server);

  app.configure(function() {
    app.use(express.logger("dev"));
    app.use(express["static"](__dirname + "/public"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  app.get('/bookmarklet', function(req, res) {
    return res.send("Make this a bookmarklet: javascript:(function()%7Bvar%20_wsr=document.createElement('script');%20_wsr.type='text/javascript';%20_wsr.src='/wsreload.js';%20document.getElementsByTagName('head')%5B0%5D.appendChild(_wsr);%7D());");
  });

  app.get('/wsreload.js', function(req, res) {
    return res.sendFile("wsreload.js");
  });

  app.get('/reload', function(req, res) {
    return io.sockets.emit('reload');
  });

  console.log("Express server listening on port 2000");

}).call(this);
